name: CI/CD Pipeline
on: 
  push:
    branches:
      -main
  jobs:
    deploy:
       runs-on: ubuntu-latest

       steps:
        -name: Deploy to server
         uses: appleboy/ssh-action@v1.0.0

        -name: Deploy to server
         run: 
          echo "Deploying.."
        with:
          host: ${{secrets.SERVER_IP }}
          username: ${{secrets.USER }}
          key: ${{secrets.SSH_KEY }}
          script: |
            cd/home/tuanvo/myapp
            git pull
            bash deploy.sh






m
